### ISSUE TITLE
CSV of stations list cannot be loaded

### ISSUE THREAD

**Issue by GabrielVareilles** [paulRbr/gares#7]
I have the same pb as @Tristram, we have an error 404 on the csv.

```
GARES_LIST_URL = "https://raw.githubusercontent.com/paulrbr/stations/stations-with-bls/stations.csv"
```

"Gem Load Error is: 404 Not Found"

Opened Pull request from Tristramg will correct this issue #6 .

Other Possible fixes: 
- Add csv file or better a json or geojson directly to the gem assets
- Get station list from Sncf open data api

**Comment by paulRbr** [comment]
Hi @GabrielVareilles!

Thanks for mentioning the issue. I guess your first proposition would be the best idea: include the station list asset in the gem.

For now I've fixed the 404 error by merging in the PR #6.

I'll close this issue as it was related to the error that is now fixed. If you want to propose some changes on how the list of stations are fetched please do not hesitate to contribute :).
